{% set name = "poselib" %}
{% set version = "2.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/PoseLib/PoseLib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: caa0c1c9b882f6e36b5ced6f781406ed97d4c1f0f61aa31345ebe54633d67c16
    patches:
      - unvendor_pybind11.patch
      - fix_windows.patch
      - fix_compile_options.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make                                   # [unix]
    - ninja
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - pip
    - setuptools
    - python
    - pybind11
    - eigen
  run:
    - python
    - numpy

test:
  imports:
    - poselib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PoseLib/PoseLib
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: PoseLib provides a collection of minimal solvers for camera pose estimation.

extra:
  recipe-maintainers:
    - Tobias-Fischer
